export const UPDATE_ACCORDION_ID = "UPDATE_ACCORDION_ID";
export const NEXT_ACCORDION = "NEXT_ACCORDION";
export const PREV_ACCORDION = "PREV_ACCORDION";
export const COMPLETED_STEPS = "COMPLETED_STEPS";
export const SET_MASTER_DATA = "SET_MASTER_DATA";
export const GET_MASTER_DATA = "GET_MASTER_DATA";
